export const ADMIN_ROLES = [
  "superadmin",
  "executive",
  "founder",
  "ceo",
  "managing-director",
  "operations-manager",
  "project-manager",
  "product-manager",
  "technical-lead",
  "developer",
  "designer",
  "qa-tester",
  "marketing",
  "sales",
  "customer-support",
  "accountant",
  "finance-manager",
  "hr-manager",
  "recruiter",
  "legal-counsel",
  "business-analyst",
  "content-manager",
  "social-media-manager",
  "intern",
  "viewer",
] as const;

export type AdminRole = (typeof ADMIN_ROLES)[number];

export const PLATFORM_PERMISSIONS = [
  "users.create",
  "users.update",
  "users.suspend",
  "users.activate",
  "users.assign_role",
  "users.assign_permissions",
  "teams.manage",
  "departments.manage",
  "projects.view_all",
  "projects.manage",
  "finance.view",
  "finance.manage",
  "hr.view",
  "hr.manage",
  "legal.view",
  "legal.manage",
  "announcements.manage",
  "reports.manage",
  "audit.view",
  "rbac.manage",
] as const;

export type PlatformPermission = (typeof PLATFORM_PERMISSIONS)[number];

export const ROLE_DEFAULT_PERMISSIONS: Record<AdminRole, PlatformPermission[]> = {
  superadmin: [...PLATFORM_PERMISSIONS],
  founder: [...PLATFORM_PERMISSIONS],
  ceo: [...PLATFORM_PERMISSIONS],
  "managing-director": [...PLATFORM_PERMISSIONS],
  executive: [
    "users.create",
    "users.update",
    "users.suspend",
    "users.activate",
    "users.assign_role",
    "teams.manage",
    "departments.manage",
    "projects.view_all",
    "projects.manage",
    "finance.view",
    "hr.view",
    "legal.view",
    "announcements.manage",
    "reports.manage",
    "audit.view",
  ],
  "operations-manager": ["users.update", "projects.manage", "teams.manage", "reports.manage"],
  "project-manager": ["projects.manage", "projects.view_all", "reports.manage"],
  "product-manager": ["projects.manage", "reports.manage"],
  "technical-lead": ["projects.manage"],
  developer: [],
  designer: [],
  "qa-tester": [],
  marketing: [],
  sales: [],
  "customer-support": [],
  accountant: ["finance.view"],
  "finance-manager": ["finance.view", "finance.manage", "reports.manage"],
  "hr-manager": ["users.create", "users.update", "users.suspend", "users.activate", "hr.manage", "teams.manage"],
  recruiter: ["users.create", "hr.view"],
  "legal-counsel": ["legal.view", "legal.manage"],
  "business-analyst": ["reports.manage"],
  "content-manager": ["announcements.manage"],
  "social-media-manager": ["announcements.manage"],
  intern: [],
  viewer: [],
};

