export const FEATURE_KEYS = [
  "team-management",
  "hr-dashboard",
  "employee-profiles",
  "tasks",
  "projects-management",
  "financial-dashboard",
  "sales-analytics",
  "marketing-campaigns",
  "legal-documents",
  "performance-analytics",
  "notifications-center",
  "internal-messaging",
  "meetings-scheduling",
  "permissions-manager",
  "activity-monitoring",
  "recruitment-pipeline",
  "support-tickets",
  "content-management",
  "product-roadmap",
  "qa-workflows",
  "goals",
  "approvals",
  "calendar",
  "checkins",
  "announcements",
  "wiki",
  "reports",
  "accountability",
  "progress",
  "trust",
  "burnout",
  "timeline",
  "alerts",
  "integrations",
  "ai-assistant",
  "audit",
  "os",
] as const;

export const FEATURE_KEY_SET = new Set<string>(FEATURE_KEYS);
